version: '3.1'

services:
  mysql:
   image: mysql
   platform: linux/amd64
   restart: always
   container_name: db-mysql
   ports:
    - 3307:3306
   environment:
     MYSQL_DATABASE: userdata
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USER: testuser
     MYSQL_PASSWORD: testpassword
   volumes:
    - ./db:/docker-entrypoint-initdb.d